config/routes.rb
Rails.application.routes.draw do
  get 'competitions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'pages#home'

  # PAGES ROUTES
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  # CLUBS ROUTES
  #   get "clubs", to: "clubs#index"
  #   get "clubs/new", to: "clubs#new" # #new needs to be before #show otherwise rails will think that "new" is an id
  #   get "clubs/:id", to: "clubs#show", as: :club
  #   post "clubs", to: "clubs#create"
  #   get "clubs/:id/edit", to: "clubs#edit", as: :edit_club
  #   patch "clubs/:id", to: "clubs#update"
  #   delete "clubs/:id", to: "clubs#destroy"
    # or
  #   resources :clubs
  resources :clubs, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :clubs do
    resources :competitions, only: [:new, :create]
  end
  resources :competitions, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :competitions, dependent: :destroy
end

app/models/competition.rb
class Competition < ApplicationRecord
  belongs_to :club

  validates :start_date, presence: true
  validates :length_in_days, presence: true
  validates :winner, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    # => Fetch a club
    before_action :set_club, only: [:show, :edit, :update, :destroy]

    def index
        # => Fetch clubs
        @clubs = Club.all
    end

    def show
        # help to debug
        # raise
        # then im the console you can see the params by typing "params"

        # => Fetch a club -> Done in Private
    end
p
    def new
        # => Create a new club
        @club = Club.new
    end

    def create
        # TODO - Add the logo to the club
        # @club = Club.new(params[:club].permit(:name, :description, :logo))

        # => Create a new club
        @club = Club.new(params[:club].permit(club_params))
        if @club.save
            redirect_to clubs_path
        else
            render :new
        end
    end

    def edit
        # => Fetch a club -> Done in Private
    end

    def update
        # => Fetch a club
        # @club = Club.find(params[:id]) is done by the before_action
        if @club.update(params[:club].permit(:name, :description))
            redirect_to club_path(@club)
        else
            render :edit
        end
    end

    def destroy
        # => Fetch a club -> Done in Private
        @club.destroy
        redirect_to clubs_path, status: :see_other
    end

    private

    def set_club
        @club = Club.find(params[:id])
    end

    def club_params
        params.require(:club).permit(:name, :description).require(:name)
    end

end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_club, only: [:new, :create]

  def show
    @competition = Competition.find(params[:id])
  end

  def new
    @competition = Competition.new
  end

  def create
    # Create a new competition from the form data
    @competition = Competition.new(competition_params)
    # Set the club for the competition
    @competition.club = @club # No need to mention the id of the club because of the belongs_to association in the Competition model (club_id)

    if @competition.save
      # Redirect to the club page
      redirect_to club_path(@club)
    else
      # Render the new competition form again
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy
    redirect_to club_path(@competition.club), status: :see_other  # We are using the club method in the competition model to get the club of the competition, that's why in the route we don't need to pass the club_id
  end

  private

    def competition_params
        params.require(:competition).permit(:start_date, :length_in_days, :winner)
    end

    def set_club
      @club = Club.find(params[:club_id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        # => Fetch clubs
        @clubs = Club.all
    end

    def about
        # => Fetch members of the team
        @members = ['brian', 'clement', 'romain']
        # Member.all

        # raise

        if params[:member]
            @members = @members.select { |member| member.start_with?(params[:member]) }
        end
    end

    def contact
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clubs/_form.html.erb
<%= form_with model: @club do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/clubs/edit.html.erb
<%# Create your club %>
<h1>Edit Club</h1>

<%# partial %>
<%= render 'form', club: @club %>

<hr>
<%# back to this club %>
<%= link_to "Back to this club", club_path(@club) %>

app/views/clubs/index.html.erb
<h1>Clubs</h1>

<%# Create a new club: %>
<%= link_to "Create a new club", new_club_path %>

<ul>
<% @clubs.each do |club| %>
  <li>
    <%# link %>
    <%= link_to club.name, club_path(club) %>:
    <span><%= club.description %></span>
    <br>
    <br>
  </li>
<% end %>
</ul>

app/views/clubs/new.html.erb
<%# Create your club %>
<h1>Create a new Club</h1>
<%# partial %>
<%= render 'form', club: @club %>

app/views/clubs/show.html.erb
<!-- app/views/clubs/show.html.erb -->
<h1><%= @club.name %></h1>
<p><%= @club.description %></p>

<p><strong>Competitions</strong></p>
<ul class="list-group">
  <% @club.competitions.each do |the_competition| %>
    <li class="list-group-item">Starting the <%= the_competition.start_date %> - for <%= the_competition.length_in_days %> days, AND THE WINNER is <%= the_competition.winner %></li>
    <%= link_to "Delete",
      competition_path(the_competition),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %>
  <% end %>
</ul>

<%# Edit %>
<%= link_to "Edit", edit_club_path(@club) %>

<%# Delete %>
<%= link_to "Delete", club_path(@club), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

<hr>
<%# back to all clubs %>
<%= link_to "Back to all clubs", clubs_path %>

app/views/competitions/new.html.erb
<h1>New Competition</h1>
<!-- app/views/reviews/new.html.erb -->
<%= simple_form_for [@club, @competition] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :length_in_days %>
  <%= f.input :winner %>
  <%= f.submit "Submit competition", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpinSociety</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header class="navbar">
        <h1><%= link_to "Spin Society", root_path, alt: "Home" %></h1>
        <nav>
          <%= link_to "Home", root_path, alt: "Home" %>
          <%= link_to "About", about_path, alt: "About" %>
          <%= link_to "Clubs", clubs_path, alt: "Clubs" %>
          <%= link_to "Contact", contact_path, alt: "Contact" %>
        </nav>
    </header>
    <hr>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<form action="/about" method="get">
  <input type="text" name="member" value="<%= params[:member] %>" placeholder="Who are you looking for?">
  <input type="submit">
</form>

<ul>
  <% @members.each do |member| %>
    <li><%= member.upcase %></li>
  <% end %>
</ul>

app/views/pages/contact.html.erb
<h1>Contact</h1>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Welcome to the home page!</p>